version : '3'

services :
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'groceryapp_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'aaeBae2020~'
      MYSQL_ROOT_PASSWORD: 'aaeBae2020~'
    volumes:
      - grocerydata:/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/groceryapp
    depends_on:
      - db
volumes:
  grocerydata: