version : '3'

services :
  db:
    image: mysql:5.7
    ports:
      - '3307:3307'
    environment:
      MYSQL_DATABASE: 'groceryapp'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'aaeBae2020~'
      MYSQL_ROOT_PASSWORD: 'aaeBae2020~'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/groceryapp
    depends_on:
      - db