# Generated by Django 3.1.4 on 2021-01-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField()),
                ('address_line_2', models.TextField(null=True)),
                ('city', models.CharField(max_length=50)),
                ('post_code', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=17, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('logo', models.ImageField(upload_to='brand_logos/')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=17, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_cart_empty', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category_logo', models.ImageField(default='../../category_logos/Amul.png', upload_to='category_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('payment_date', models.DateTimeField()),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.brand')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.main_category')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_image', models.ImageField(upload_to='update_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category_logo', models.ImageField(default='../../sub_cat_logos/Amul.png', upload_to='sub_category_logos/')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.main_category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_in_stock', models.PositiveIntegerField()),
                ('unit', models.CharField(default='grams', max_length=20)),
                ('unit_weight', models.DecimalField(decimal_places=2, help_text='Enter the weight in grams', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Enter the value in format dollars.cents', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_details', to='groceryapi.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.sub_category'),
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_purchased', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.order')),
                ('product_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.product_details')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_purchased', models.PositiveIntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='groceryapi.customer')),
                ('product_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_details', to='groceryapi.product_details')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.customer'),
        ),
    ]
