# Generated by Django 3.1.4 on 2020-12-29 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0003_auto_20201229_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+61999999999'. Up to 11 digits allowed.", regex='/^(?:\\(?(?:\\+?61|0)4\\)?(?:[ -]?[0-9]){7}[0-9]$)/')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+61999999999'. Up to 11 digits allowed.", regex='/^(?:\\(?(?:\\+?61|0)4\\)?(?:[ -]?[0-9]){7}[0-9]$)/')]),
        ),
    ]
