# Generated by Django 3.1.4 on 2021-01-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0004_auto_20201229_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='unit',
            field=models.CharField(default='grams', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
