# Generated by Django 3.1.4 on 2021-01-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0005_auto_20210116_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_type',
            field=models.CharField(default='-', max_length=60),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='Grocery', max_length=60),
        ),
    ]
