# Generated by Django 3.1.4 on 2021-01-18 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0006_auto_20210116_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_details', to='groceryapi.product'),
        ),
    ]
