# Generated by Django 3.1.4 on 2021-01-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0008_auto_20210120_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product_details_id',
        ),
    ]
