# Generated by Django 3.1.4 on 2021-01-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0009_auto_20210121_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
