# Generated by Django 3.1.4 on 2021-01-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0010_remove_cart_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_image', models.ImageField(upload_to='update_images/')),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_logo',
            field=models.ImageField(default='../../brand_logos/Amul.png', upload_to='category_logos/'),
        ),
    ]
