# Generated by Django 3.1.4 on 2021-01-21 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0011_auto_20210121_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updates',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='updates',
            name='start_date',
        ),
    ]
